<?xml version="1.0" encoding="UTF-8"?>
<definitions
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
            xmlns:tns="http://eiim.service112.iskratel.si/"
            xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
            name="Integration112"
            targetNamespace="http://eiim.service112.iskratel.si/"
            xmlns="http://schemas.xmlsoap.org/wsdl/"
    >
    <types>
        <xs:schema
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://eiim.service112.iskratel.si/"
            targetNamespace="http://eiim.service112.iskratel.si/"
            elementFormDefault="qualified"
            >
            <!-- Базовые типы -->
            <xs:element form="unqualified" name="Code" type="xs:string"/>
            <xs:element form="unqualified" name="CodeDescr" type="xs:string"/>
            <xs:element name="UpdateCardResponse" type="tns:UpdateCardResponse"/>
            <!-- UpdateCardResponse -->
            <xs:complexType name="UpdateCardResponse">
                <xs:sequence>
                    <xs:element form="unqualified" name="Code" type="xs:string"/>
                    <xs:element form="unqualified" name="CodeDescr" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </types>

    <message name="UpdateCardResponse">
        <part name="parameters" element="tns:UpdateCardResponse"/>
    </message>

    <!-- Порт типа -->
    <portType name="TspgPortType">
        <operation name="UpdateCard">
            <output message="tns:UpdateCardResponse"/>
        </operation>
    </portType>

    <!-- Привязки -->
    <binding name="TspgBinding" type="tns:TspgPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="UpdateCard">
            <soap:operation soapAction="http://eiim.service112.iskratel.si/UpdateCard"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <!-- Сервис -->
    <service name="Integration112">
        <port name="TspgPort" binding="tns:TspgBinding">
            <soap:address location="http://eiim.service112.iskratel.si/"/>
        </port>
    </service>

</definitions>