title:        The node-xml-toolkit Developer's Guide
remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true
    h_min:   1
    h_max:   3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true    